### ISSUE TITLE
Add support for cage

### ISSUE THREAD

**Issue by jaritheman** [jayanam/jbake-tools#1]
Consider adding support for cage - many times when you have some wrinkles and narrow cracks in your model (like upper eye lids meeting the eye socket or between closed lips), you need a cage object to not get incorrect normals when baking. I suppose UI wise this would just be exposing the "use cage" checkbox and then add another object selector for the cage.

**Comment by jayanam** [comment]
Hi and thx for the feedback. The points you made seem all legit to me, but it would really be great if you could add these to separate issues so that we can discuss on each of them. Thx.

**Comment by jaritheman** [comment]
Done! =)

**Comment by jayanam** [comment]
Alright, great.

**Comment by jayanam** [comment]
I will add it like you suggested

**Comment by jayanam** [comment]
Added to 0.3.0

**Comment by jaritheman** [comment]
How do I get to test 0.3.0? I re-downloaded the repo as zip and installed, but I dont see the new features..

**Comment by jayanam** [comment]
Blender has a bug for re-install sometimes. I suggest deinstall the addon.
Close and reopen Blender, install the new one.

**Comment by jaritheman** [comment]
No luck...even after uninstalling and restarting Blender I cannot see anything new, like the support for cage..

![image](https://user-images.githubusercontent.com/3398212/103373848-b84a3c00-4ade-11eb-86ea-4c08f794f100.png)

**Comment by jayanam** [comment]
Ok, but the UI you pasted shows the Use Cage option.

**Comment by jaritheman** [comment]
eh, yeah I noticed that too, and removed the comment like 10 secs after posting it =P I guess I somehow expected the cage option to be located in the top of the UI with the low and high res fields and missed it.

**Comment by jayanam** [comment]
No prob
