### ISSUE TITLE
Error in Blender 2.91

### ISSUE THREAD

**Issue by GestampfteMaus** [jayanam/jbake-tools#10]
Thanks for writing this plugin in the first place! Very nice!
However: I'm not sure if Blender 2.91 is supported, but I at least wanted you to be aware that it's not working at the moment.

I get this error: 

```
Python:` Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\jbake-tools-main\jb_operators.py", line 116, in execute
    self.bake_normal_map()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\jbake-tools-main\jb_operators.py", line 57, in bake_normal_map
    bpy.ops.object.bake(type="NORMAL", use_selected_to_active=True)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: No valid selected objects


location: <unknown `location>:-1
```

**Comment by jayanam** [comment]
Hm, works for me, could you attach or send your project please?

**Comment by GestampfteMaus** [comment]
Ok, strange. To be sure, I've tried it with a simple cube and beveled cube. So that was the scene I've tested it with. Let me first grab a vanilla blender and see if it's still happening on my side. I am running some add-ons (of course ;)). Gimme a minute, get back to you soon.

**Comment by GestampfteMaus** [comment]
Hey Jayanam, I'm sorry. My bad; it IS working in 2.91 vanilla. so you can close and ignore this. I guess it's conflicting with something I changed.

Thank you for the swift response though and sorry to waste your time =)
