### ISSUE TITLE
new blender

### ISSUE THREAD

**Issue by jodamajster** [jayanam/jbake-tools#16]
will it be updated to 3.0+?

**Comment by jayanam** [comment]
Did you try? Works for me on 3+

**Comment by jodamajster** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\Jurek\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\jbake-tools-main\jb_operators.py", line 90, in execute
    self.create_normal_map(node_tree, pri_shader_node)
  File "C:\Users\Jurek\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\jbake-tools-main\jb_operators.py", line 116, in create_normal_map
    normal_map_node = self.create_normal_map(node_tree)
TypeError: create_normal_map() missing 1 required positional argument: 'pri_shader_node'

location: <unknown location>:-1

ye does not work

**Comment by henrikmyl** [comment]
I confirm this error. Jbake 0.3.0.2 not working blender 3.0.1. I'm getting the same error message. 

Image of an error message

https://i.postimg.cc/TYSrgFHd/error.png

**Comment by jayanam** [comment]
Ok thx, will have a look!

**Comment by jayanam** [comment]
Ok, fixed in version 0.3.0.3.

**Comment by jayanam** [comment]
Uninstall previous version and install new one
